# Generated by Django 5.1.15 on 2026-06-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='founder_message',
            field=models.TextField(blank=True, help_text='A short note from the founder shown on the About page.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_photo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_role',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
