# Generated by Django 5.1.15 on 2026-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_founder_message_sitesetting_founder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('annual_report', 'Annual Report'), ('financial', 'Financial Statement'), ('certificate', 'Registration / Certificate'), ('policy', 'Policy'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('category', '-uploaded'),
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered legal name, if different from the display name.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='reg_12a_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='12A registration no.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='reg_80g_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='80G registration no.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Trust / Society / Section 8 registration number.', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
    ]
